### ISSUE TITLE
Can i run it in windows?

### ISSUE THREAD

**Issue by onyedika135** [wuseman/WBRUTER#3]
I love this script. Much thanks.
**Please can i run this your script in windows?**
How?

**Comment by wuseman** [comment]
Hello.

Yes, on Windows 10 it is possible to run this if you have bash or linux installed, for install a bash shell you can do as following:

    

1.  Open settings in start menu
2. Click on Update & security.
3. Click on For Developers.
4. On the message box that will popp, click Yes to turn on developer mode.
5. After the necessary components install, you'll need to restart your computer.
6. Once your computer reboots, open Control Panel.
7. Click on Programs under Programs and Features.
8. Check the Windows Subsystem for Linux (beta) option.
9. Once the components installed on your computer, click the Restart now button to complete the task.

After your computer restarts, you will notice that Bash will not appear in the "Recently added" list of apps, this is because Bash isn't actually installed yet. Now that you have setup the necessary components, use the following steps to complete the installation of Bash:

Open Start, do a search for bash.exe, and press Enter.

On the command prompt, type y and press Enter to download and install Bash from the Windows Store.

Then you'll need to create a default UNIX user account. This account doesn't have to be the same as your Windows account. Enter the username in the required field and press Enter (you can't use the username "admin").
Close the "bash.exe" command prompt.

Now that you completed the installation and setup, you can open the Bash tool from the Start menu like you would with any other app.

Now inside shell you can copy and paste:
git clone https://github.com/wuseman/WBRUTER
cd WBRUTER; ./wbruter 

And now you will see 

           ___
          |   |        -a|--android     - Brute force attack an android device with 100% guarantee to crack pin
         _|___|_       -A|--androidgui  - Brute force attack android device via gui/login screen (OLD METHOD)
          (* *)        -f|--ftp         - Dictionary attack for any ftp/ftps server
         __)#(__       -g|--gmail       - Dictionary attack for gmail accounts
        ( )...( )(_)   -G|--gpg         - Dictionary attack for break the encryption of gpg files
        || |_| ||//    -h|--help        - Print this help, duh!
     >==() | | ()/     -r|--rar         - Dictionary attack for break the encryption of rar files
         _(___)_       -s|--ssh         - Dictionary attack for break ssh login
        [-]   [-]      -z|--zip         - Brute force and dictionary attack a zip encryptedfile
                       -Z|--znc         - Dictionary attack for znc bouncer login (web)
     ~~~~~~~~~~~~~~~~


For find more info how to install bash on Windows with pictures [here](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10")

**Comment by onyedika135** [comment]
Thank you so much.
let me try it now
